### ISSUE TITLE
Mise à jour PostgreSQL

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#115]
Mettre à jour la configuration docker pour utiliser une image plus récente de PostgreSQL (16+)

**Comment by rv2931** [comment]
Le souci c'est que passer à du postgres pose des porblème de compatibilité avec les données
J'ai une erreur `"The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 16.2"` au lancement du conteneur

et je peux même pas gérer ça dans le conteneur init vu que le conteneur postgres ne se lance pas
Idem avec une 15 `The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.6.'`

A priori pour faire ça proprement va falloir créer un job docker/commande de migration dédié
https://pankajconnect.medium.com/how-to-migrate-your-postgresql-database-to-docker-a-practical-guide-6014fb066b8f

**Comment by rv2931** [comment]
Ok.
Je pense qu'il y a moyen de faire une migration de donnée "assistée" avec une stack docker compose dédiée du genre:

`docker compose -f docker-compose-migrate-data.yaml up`
Et un fichier docker-compose-migrate-data.yml qui ressemblerait à ça faut juste fixer le nom du volume postgres utilisé dans la stack standard pour qu'il soit le même que le volume migré):
```
x-common-infos:
  # Env variables stored in a .env file at same level than docker-compose.yaml
  environment: &common-env
    POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres_bloom}
    POSTGRES_DB: ${POSTGRES_DB:-bloom_db}
    POSTGRES_USER: ${POSTGRES_USER:-bloom_user}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bloom}
    LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}

services:

  postgres-14:
    container_name: postgres_bloom_14
    image: ${POSTGIS_IMAGE:-postgis/postgis:14-3.3-alpine}
    environment:
      <<: *common-env
    networks:
        - bloom_net
    healthcheck:
      test: ['CMD-SHELL', "pg_isready --quiet --dbname=$${POSTGRES_DB:-bloom_db} --username=$${POSTGRES_USER:-bloom_user}"]
      interval: 100ms
      timeout: 14s
      retries: 140
      start_period: 0s
      
  
  postgres-16:
    container_name: postgres_bloom_16
    image: ${POSTGIS_IMAGE:-postgis/postgis:16}
    environment:
      <<: *common-env
    networks:
        - bloom_net
    healthcheck:
      test: ['CMD-SHELL', "pg_isready --quiet --dbname=$${POSTGRES_DB:-bloom_db} --username=$${POSTGRES_USER:-bloom_user}"]
      interval: 100ms
      timeout: 14s
      retries: 140
      start_period: 0s


  dump-postgres-14:
    container_name: migrate_from_14
    image: ${POSTGIS_IMAGE:-postgis/postgis:14-3.3-alpine}
    environment:
      <<: *common-env
    networks:
        - bloom_net
    volumes:
        #- bloom-data-migration-14:/var/lib/postgresql
        - ./data/migration:/migration
    command: >
        sh -c "
            export PGPASSWORD=${POSTGRES_PASSWORD}
            pg_dump --host postgres-14 -U ${POSTGRES_USER} --dbname ${POSTGRES_DB} > /migration/dump-14.sql
            "
    depends_on:
      postgres-14:
        condition: service_healthy
   
  restore-postgres-16:
    container_name: migrate_to_16
    image: ${POSTGIS_IMAGE:-postgis/postgis:16}
    environment:
      <<: *common-env
    networks:
        - bloom_net
    volumes:
        - bloom-postgres:/var/lib/postgresql
        - ./data/migration:/migration
    command: >
        sh -c "
            export PGPASSWORD=${POSTGRES_PASSWORD}
            psql --host postgres-16 -U ${POSTGRES_USER} --dbname ${POSTGRES_DB} < /migration/dump-14.sql
            "
    depends_on:
      postgres-16:
        condition: service_healthy
      dump-postgres-14:
        condition: service_completed_successfully

networks:
  bloom_net:
    name: bloom_net
    
volumes:
    bloom-data-migration-share:
    bloom-postgres:
```

Mise à jour du docker-compose.yaml standard:

```
[...]
  postgres:
[...]
    volumes:
        - bloom-postgres:/var/lib/postgresql
[...]
    
volumes:
    bloom-postgres:
```
